name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file - NewLink modifications
version: 2.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  meta: ^1.10.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.9
